spring:
  cloud:
    openfeign:
      client:
        config:
          currency:
            url: http://api.nbp.pl/api/exchangerates/tables/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
